<?php
/**
 * @file
 * Enables the upload of webform submissions from a delimited file.
 *
 * This is usefull for importing results from other systems in to Webform.
 *
 * @author John C Jemmett <jjemmett@northwind-inc.com>
 * @author Greg Bosen <gbosen@northwind-inc.com>
 * @author Joe Corall <joe.corall@gmail.com>
 *
 */

/**
 * Implements hook_menu().
 */
function webform_import_menu() {
  $items = array();
  $items['node/%webform_menu/webform-results/upload'] = array(
    'title' => 'Upload',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('webform_import_form', 1),
    'access arguments' => array('access webform upload'),
    'weight' => 10,
    'type' => MENU_LOCAL_TASK,
  );
  $items['node/%webform_menu/webform-results/upload/%'] = array(
    'title' => 'Get Template',
    'page callback' => 'webform_import_csvtemplate',
    'page arguments' => array(1, 4),
    'access arguments' => array('access webform upload'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function webform_import_permission() {
  return array(
    'access webform upload' => array(
      'title' => t('Access Webform Upload'),
      'description' => t('Grants access to the Upload tab on all webform content.'),
      'restrict access' => TRUE,
    ),
  );
}

/**
 * Creates a downloadable CSV template file corresponding to a Webform structure.
 *
 * @param $node
 *   The current webform node.
 * @param $type
 *   The type of delimited file template to download.
 */
function webform_import_csvtemplate($node, $type) {
  $types = _webform_import_field_key_options();
  $filename = check_plain($node->title) . '_upload.csv';
  $headers = array();
  $node->webform['components']['-1'] = array(
    'name' => 'Submission ID',
    'form_key' => 'SID',
  );
  if (array_key_exists($type, $types)) {

    foreach ($node->webform['components'] as $cid => $component) {
      $ctype = ( array_key_exists('type',$component) ? $component['type'] : '' );
      if ($ctype != 'file' && $ctype != 'fieldset' && $ctype != 'markup' && $ctype != 'pagebreak') {
        $headers[] = $component[$type];
      }
    }
    // @TODO Make this line more generic.
    $headers[] = ($type=='name') ? 'Submitted Time' : 'submitted_time';
    $csv = join(',', $headers);

    backdrop_add_http_header('Content-Type', 'application/force-download');
    backdrop_add_http_header('Pragma', 'public');
    backdrop_add_http_header('Cache-Control', 'max-age=0');
    backdrop_add_http_header('Content-Type', 'text/csv');
    backdrop_add_http_header('Content-Disposition', "attachment; filename=$filename");
    print $csv;
  }
  else {
    backdrop_set_message(t('Invalid header type.'), 'warning');
    $path = explode('/', $_GET['q']);
    array_pop($path);
    $path = join('/', $path);
    backdrop_goto(backdrop_get_path_alias($path));
  }
}

/**
 * Client form generation function. Allows the user to upload a delimited file.
 *
 * @param $form_state
 *   The current form values of a submission, used in multipage webforms.
 * @param $node
 *   The current webform node.
 *
 * @see webform_import_form_submit()
 * @ingroup forms
 */
function webform_import_form($node, $form_state) {
  $node = $form_state['build_info']['args'][0];

  // Add a css class for all client forms.
  $form['#attributes'] = array('class' => 'webform-import-form');

  // Set the encoding type (necessary for file uploads).
  $form['#attributes']['enctype'] = 'multipart/form-data';

  $form['#redirect'] = 'node/' . $node->nid . '/webform-results/table';

  $form['#submit'][] = 'webform_import_form_submit';
  $form['details']['nid'] = array(
    '#type' => 'value',
    '#value' => $node->nid,
  );

  $button_text = t('Download template');
  $upload_path = 'node/' . $node->nid . '/webform-results/upload/';
  $button_optopns = array('attributes' => array('class'=>'button'));
  $name_button = l($button_text, $upload_path . 'name', $button_optopns);
  $key_button = l($button_text, $upload_path . 'form_key', $button_optopns);

  $component_table = array();
  $component_table['header'] = array(
    array('data' => t('Field Names') . '&nbsp;<div class="move-right"> ' . $name_button . ' </div>'),
    array('data' => t('Field Form Keys') . '&nbsp;<div class="move-right"> ' . $key_button . ' </div>'),
  );
  $component_table['rows'] = array();
  $component_table['rows'][] = array('Submission ID', 'SID');
  foreach ($node->webform['components'] as $cid => $component) {
    if ($component['type'] == 'file' || $component['type'] == 'fieldset'|| $component['type'] == 'markup' || $component['type'] == 'pagebreak') {
      continue;
    }
    $style = '';
    if (isset($component['required'])) {
      $style = 'font-weight: bold';
    }
    $component_table['rows'][] = array(
      array('data' => $component['name'], 'style' => $style ),
      array('data' => $component['form_key'], 'style' => $style ),
    );
  }
  // Add Submission Date - will be used if present in the file
  $component_table['rows'][] = array(
    array('data' => 'Submitted Time', 'style' => $style ),
    array('data' => 'submitted_time', 'style' => $style ),
  );

  $form['header'] = array(
    '#type' => 'item',
    '#markup' => '<h2>' . t('Webform Import for "@title"', array('@title' => $node->title)) . '</h2>',
  );

  $form['help'] = array(
    '#type' => 'help',
    '#markup' => t('Webform import enables the upload of delimited files to enter submission data.'),
  );

  $form['instructions'] = array(
    '#type' => 'fieldset',
    '#title' => t('Instructions'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
  );

  $instructions_items = array(
    'type' => 'ol',
    'items' => array(
      'All rows with a submission id (SID) will be updated. Those without a submission id will be inserted.',
      'All rows without submitted time will be inserted with current system time.',
      array(
        'data' => 'Component specific help:',
        'children' => array(
          '<strong>Date</strong>: must be in a format parsable by the php function <code>strtotime()</code> Any time data will be discarded.',
          '<strong>Grid</strong>: option keys must be separated by commas and in the order of the questions in the webform. (e.g., <em>"red,male,car"</em> for the questions <em>"Favorite color, Gender, Type of automobile you drive"</em> respectively.)',
          '<strong>File</strong>: * currently unable to handle this component.',
          '<strong>Select</strong>: for multiselect answer keys must be separated by commas. (e.g., <em>"1,2,3"</em>)',
          '<strong>Time</strong>: must be in a format parsable by the php function <code>strtotime()</code> Any date data will be discarded.',
        ),
      ),
      'Only data entry fields are importable. Excluded component types include: fieldset, markup &amp; pagebreak.',
      'The file must use the following values for column headers, anything else will be ignored. &nbsp;<small>* bold names are mandatory and must contain a value</small>',
    ),
  );

  $markup  = '<div class="webform-import-instructions">';
  $markup .=    theme('item_list', $instructions_items);
  $markup .=    theme('table', $component_table);
  $markup .= '</div>';

  $path = backdrop_get_path('module', 'webform_import');
  $form['instructions']['instructions'] = array(
    '#type' => 'item',
    '#markup' => $markup,
    '#attached' => array(
      'css' => array($path . '/css/webform-import-admin.css'),
    ),
  );

  $form['upload'] = array(
    '#type' => 'file',
    '#title' => t('Delimited data file'),
    '#description' => t('Choose the data file containing the data you want uploaded. All rows with a submission id (SID) will be updated. Those without a submission id will be inserted.')
  );

  $form['delimiter'] = array(
    '#type' => 'select',
    '#title' => t('File Delimiter'),
    '#default_value' => ',',
    '#options' => _webform_import_delimiter_options(),
    '#description' => t('Delimiter for file being uploaded.'),
  );

  $form['field_keys'] = array(
    '#type' => 'select',
    '#title' => t('Column header contains'),
    '#default_value' => 'name',
    '#options' => _webform_import_field_key_options(),
    '#description' => t('What to use for the column key. (You probably want to choose form key if you have multiple fields with the same name.)'),
  );

  $form['actions'] = array(
    '#type' => 'actions',
  );

  // Add the submit button.
  $form['actions']['submit'] = array(
    '#type' => 'submit',
    '#value' => empty($node->webform['submit_text']) ? t('Import') : $node->webform['submit_text'],
    '#weight' => 10,
  );

  return $form;
}

/**
 * Form submission function to parse the delimited file and add to the database.
 *
 * @param $form
 *   The current form.
 * @param $form_state
 *   The current form values of a submission.
 *
 * @see webform_import_form()
 */
function webform_import_form_submit($form, $form_state) {

  // Define your limits for the submission here.
  $limits = array(
    'extensions' => 'csv tsv txt'
  );
  $validators = array(
    'file_validate_extensions' => array($limits['extensions'])
  );

  if ($file = file_save_upload('upload', $validators)) {
    _webform_import_import($form, $form_state, $file);
  }
  else {
    form_set_error('upload', t('Uploaded file could not be saved.'));
    watchdog('webform-import', 'File save error. Could not save file %file to path %path.!details', array('%file' => $file->filename, '%path' => $file->filepath, '!results' => '<br />\n<pre>' . htmlentities(print_r($form_state['values'], TRUE)) . '</pre>'), WATCHDOG_ERROR);
  }
}

/**
 * Function to parse the delimited file and add submissions to the database.
 *
 * @param $form
 *   The current form.
 * @param $form_state
 *   The current form values of a submission.
 *
 * @see webform_import_form()
 */
function _webform_import_import($form, $form_state, $file) {

  // This makes php auto-detect mac line endings.
  ini_set('auto_detect_line_endings', TRUE);

  if (($handle = fopen($file->destination, 'r')) === FALSE) {
    form_set_error('upload', t('File could not be opened for reading.'));
    watchdog('webform-import', 'File read error. Could not read file %file at path %path.!details', array('%file' => $file->filename, '%path' => $file->filepath, '!results' => '<br />\n<pre>' . htmlentities(print_r($form_state['values'], TRUE)) . '</pre>'), WATCHDOG_ERROR);
    return;
  }

  module_load_include('inc', 'webform', 'includes/webform.submissions');

  $sids = array();
  $cids = array();
  $fields = array();

  $webform = node_load(intval($form_state['values']['nid']));
  $delimiter = $form_state['values']['delimiter'];
  $delimiter = $delimiter == "\t" ? "\t" : $delimiter;
  $field_key = $form_state['values']['field_keys'];

  $components_list = array();
  if ($field_key === 'name') {
    $components_list['Submission ID'] = array('form_key' => 'SID');
  }
  else {
    $components_list['SID'] = array('form_key' => 'SID');
  }
  foreach ($webform->webform['components'] as $cid => $component) {
    $component['cid'] = $cid;
    $components_list[trim($component[$field_key])] = $component;
  }

  $data = array();
  $num = 0;
  $arraylen = 0;
  $count = -1;

  while (!feof($handle)) {
    $count++;
    $data = fgetcsv($handle, 0, $delimiter);

    // Ignore empty rows.
    if ($data[0] === NULL) {
      continue;
    }

    if ($count == 0 ) { // This is the header row.
      $arraylen = count($data);
      foreach ($data as $k => &$cell_value) {
        $cell_value = _webform_import_csvfieldtrim($cell_value);
        // Identify the Key of Submitted Time
        if ($cell_value == 'Submitted Time' || $cell_value == 'submitted_time'){
          $submitted_key = $k;
          continue;
        }
        if ($cell_value && !$components_list[$cell_value]) {
          backdrop_set_message(t('Can not find column @k in components list, skipping.', array('@k' => $cell_value)), 'warning');
        }
        elseif (isset($components_list[$cell_value]['cid'])) {
          $cids[$k] = $components_list[$cell_value]['cid'];
        }
      }
      $fields = array_flip($data);

      foreach ($components_list as $k => $component) {
        if (!strcmp($k, 'name')) {
          if ($component['required'] && !isset($fields[$k])) {
            form_set_error('upload', t('Column @k is required but could not be found in this file. Alter the file or the webform and try again.', array('@k' => $k)));
          }
        }
      }

      $fields = $data;
      continue 1;
    }

    $num = count($data);
    $sid = NULL;
    $submitted = REQUEST_TIME;

    if ($arraylen == $num) {
      $sub_array = array();
      foreach ($data as $k => &$cell_value) {
        $cell_value = _webform_import_csvfieldtrim($cell_value);
        if ($cell_value == '') {
          // Checking mandatory field for a value.
          $isset = isset($components_list[$fields[$k]]['required']);
          if ($isset && $components_list[$fields[$k]]['required']) {
            $message = 'Required field has no value at row,col: @row,@column. Skipping this row!';
            backdrop_set_message(t($message, array('@row' => $count, '@column' => $k)), 'warning');
            continue 2;
          }
          else {
            continue 1;  // Skip field if empty.
          }
        }

        // Checking SID input security.
        if ($components_list[$fields[$k]]['form_key'] === 'SID') {
          if (!is_numeric($cell_value)) {
            backdrop_set_message(t('Invalid Submission ID at row,col: @row,@column.  Skipping this row!', array('@row' => $count, '@column' => $k)), 'warning');
            continue 2;
          }
          else {
            $sid = intval($cell_value); // Valid input security (integer values only).
          }
        }
        // It's a real component, parse and add to $sub_array.
        elseif (($cid = isset($cids[$k]) ? $cids[$k]:FALSE) !== FALSE) {
          $type = $components_list[$fields[$k]]['type'];
          // Date and time components.
          if ($type === 'date' || $type === 'time') {
            $timezone = date_default_timezone();
            $date = new DateTime($cell_value, new DateTimeZone($timezone));
            $timestamp = $date->format('U');
            if ($time = $timestamp) {
              $cell_value = $type === 'date' ? date('Y-m-d', $time) : date('H:i:s', $time);
            }
            else {
              backdrop_set_message(t('Invalid datetime value at row,col: @row,@column. Skipping this row!', array('@row' => $count, '@column' => $k)), 'warning');
              continue 2;
            }
          }
          // Grid and multi-select components.
          elseif ($type === 'grid' || ($type === 'select' && $components_list[$fields[$k]]['extra']['multiple'] == 1)) {
            // Explode the value into an array and associate it back to the value.
            $cell_value = explode(',', $cell_value);
          }
          $sub_array[$cid] = $cell_value;
        }

        if ($k === $submitted_key) {
          $submitted = strtotime($cell_value);
        }
      }

      global $user;
      $submission = (object) array(
        'nid' => $webform->nid,
        'uid' => $user->uid,
        'submitted' => $submitted,
        'completed' => 0,
        'modified' => REQUEST_TIME,
        'remote_addr' => webform_ip_address($node),
        'is_draft' => FALSE,
        'serial' => NULL,
        'data' => webform_submission_data($webform, $sub_array),
      );

      // Determine if INSERT or UPDATE based on inclusion of SID.
      if ($sid != NULL) {
        $submission->sid = $sid;
        $sids[] = webform_submission_update($webform, $submission);
      }
      else {
        $sids[] = webform_submission_insert($webform, $submission);
      }
    }
    else {
      backdrop_set_message(t('Row @column is malformed and will need to be fixed and resubmitted.', array('@column' => ($count+1))), 'warning');
    }
  }
  fclose($handle);

  if (!file_delete($file->fid)) {
    watchdog('webform-import', 'File could not be deleted (cleanup process). File: %file at path %path . !details', array('%file' => $file->filename, '%path' => $file->destination, '!results' => '<br />\n<pre>' . htmlentities(print_r($form_state['values'], TRUE)) . '</pre>'), WATCHDOG_ERROR);
  }

  backdrop_set_message(t('We uploaded @count submissions', array( '@count' => count($sids))));
  watchdog('webform-import', 'Submission file uploaded to %title.', array('%title' => check_plain($webform->title), '!results' => '<br />\n<pre>' . htmlentities(print_r($form_state['values'], TRUE)) . '</pre>'));

}

/**
 * Returns a list of value delimiters we can use.
 *
 * @return
 *   An array of key/value pairs for form options list.
 */
function _webform_import_delimiter_options() {
  return array(
    ',' => t('Comma (,)'),
    "\t" => t('Tab (\t)'),
    ';' => t('Semicolon (;)'),
    ':' => t('Colon (:)'),
    '|' => t('Pipe (|)'),
    '.' => t('Period (.)'),
    ' ' => t('Space ( )'),
  );
}

/**
 * Returns a list of field header types we can use.
 *
 * @return
 *   An array of key/value pairs for form options list.
 */
function _webform_import_field_key_options() {
  return array(
    'name' => t('Field Names'),
    'form_key' => t('Field Form Keys'),
  );
}

/**
 * Returns a trimmed field value
 *
 * @param $value
 *   Field value to be trimmed.
 * @return
 *   Trimmed field value.
 */
function _webform_import_csvfieldtrim($value) {
  // Remove whitespace.
  $value = trim($value);

  // Strip off the beginning and ending quotes if necessary.
  $value = trim($value, '"');

  // Remove control characters. Some editors add invalid EOL chars.
  // fgetcsv does not handle unicode characters therefore we replace them
  // manually. See http://bugs.php.net/bug.php?id=31632.
  $value = str_replace('\x00..\x1F\xfe\xff', '', $value);

  return $value;
}
